/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  User
 * Created: Jun 14, 2018
 */
Drop database VehiclePaintingSystem;
CREATE DATABASE VehiclePaintingSystem;

USE VehiclePaintingSystem;

CREATE TABLE Customer(
	CusID VARCHAR(6) NOT NULL,
	CusNIC VARCHAR(10) NOT NULL,
	CusName VARCHAR(200) NOT NULL,
	CusTel INT(10) NOT NULL,
	CONSTRAINT PRIMARY KEY(CusID)
);

CREATE TABLE Appointments(
	AID VARCHAR(6) NOT NULL,
	ADate VARCHAR(100) NOT NULL,
	Advance DECIMAL(10,2) NOT NULL,
	CusID VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY(AID),
	CONSTRAINT FOREIGN KEY(CusID) REFERENCES Customer(CusID)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CustomerPayment(
	CPID VARCHAR(6) NOT NULL,
	PayDate VARCHAR(100) NOT NULL,
	Advance DECIMAL(10,2) NOT NULL,
	PaymentAmount DECIMAL(10,2) NOT NULL,
	CONSTRAINT PRIMARY KEY(CPID),
	AID VARCHAR(6) NOT NULL,
	CONSTRAINT FOREIGN KEY(AID) REFERENCES Appointments(AID)
	ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE Service(
	SerID VARCHAR(6) NOT NULL,
	ServiceCategoryName VARCHAR(200) NOT NULL,
        CONSTRAINT PRIMARY KEY(SerID)
);

	

CREATE TABLE AppointmentDetail(
	AID VARCHAR(6) NOT NULL,
	SerID VARCHAR(6) NOT NULL,
	CusID VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY(AID,SerID,CusID),
	CONSTRAINT FOREIGN KEY(AID) REFERENCES Appointments(AID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(SerID) REFERENCES Service(SerID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(CusID) REFERENCES Customer(CusID)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Employee(
	EID VARCHAR(6) NOT NULL,
	EName VARCHAR(200) NOT NULL,
	EPos VARCHAR(200) NOT NULL,
	ETel VARCHAR(10) NOT NULL,
	EAddress VARCHAR(400) NOT NUll,
	CONSTRAINT PRIMARY KEY(EID)
);

CREATE TABLE RawMaterial(
	RCode VARCHAR(6) NOT NULL,
	Brand VARCHAR(200) NOT NULL,
	Date VARCHAR(100) NOT NULL,
	Description VARCHAR(200) NOT NULL,
	Category VARCHAR(200) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	RQTY INT(11) NOT NULL,
	Warantee VARCHAR(10) NOT NULL,
	CONSTRAINT PRIMARY KEY(RCode)
);

CREATE TABLE RawMaterialDetail(
	RCode VARCHAR(6) NOT NULL,
	EID VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY(RCode,EID),
	CONSTRAINT FOREIGN KEY(RCode) REFERENCES RawMaterial(RCode)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(EID) REFERENCES Employee(EID)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Supplier(
	SupID VARCHAR(6) NOT NULL,
	SupName VARCHAR(200) NOT NULL,
	SupTel VARCHAR(10) NOT NULL,
	SupEmail VARCHAR(200) NOT NULL,
	SupAddress VARCHAR(400) NOT NULL,
	CONSTRAINT PRIMARY KEY(SupID)
);

CREATE TABLE SupplierOrders(
	SOID VARCHAR(6) NOT NULL,
	SupID VARCHAR(6) NOT NULL,
	SupOrderDate VARCHAR(10) NOT NULL,
	SupOrderQTY INT(6) NOT NULL,
	CONSTRAINT PRIMARY KEY(SOID),
	CONSTRAINT FOREIGN KEY(SupID) REFERENCES Supplier(SupID)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SupplierOrderDetail(
	SOID VARCHAR(6) NOT NULL,
	RCode VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY(SOID,RCode),
	CONSTRAINT FOREIGN KEY(SOID) REFERENCES SupplierOrders(SOID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(RCode) REFERENCES RawMaterial(RCode)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CATEGORY(
    catID VARCHAR(6) NOT NULL,
    catName VARCHAR(100) NOT NULL,
    PRIMARY KEY(catID)
);
CREATE TABLE SupplierPayment(
	SPID VARCHAR(6) NOT NULL,
	SPDate VARCHAR(100) NOT NULL,
	SPayment DECIMAL(10,2) NOT NULL,
	SOID VARCHAR(6) NOT NULL,
	CONSTRAINT PRIMARY KEY(SPID),
	CONSTRAINT FOREIGN KEY(SOID) REFERENCES SupplierOrders(SOID)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE `user` (
       `userId` varchar(10) NOT NULL,
       `userName` varchar(100) DEFAULT NULL,
       `saltValue` varchar(256) DEFAULT NULL,
       `password` varchar(256) DEFAULT NULL,
       PRIMARY KEY (`userId`)
     ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
);
	


